[package]
name = "multiformats"
version = "0.1.0"
authors = ["prataprc <prataprc@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
unsigned-varint = "0.5.1"

[dev-dependencies]
reqwest = { version = "0.10.8", features = ["blocking"] }
parse_int = "0.4.0"
